// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoosf-EoFEBHkEBvFd0BoGh7bIedKbfbE',
    appId: '1:346213444964:android:bcf28297712b3bf0079e71',
    messagingSenderId: '346213444964',
    projectId: 'ai-assistance-4a90a',
    storageBucket: 'ai-assistance-4a90a.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Xmd3HroqHJ7v3b0JaJaUJ7GBBUk5qew',
    appId: '1:346213444964:web:09a5a8b4a1e32afe079e71',
    messagingSenderId: '346213444964',
    projectId: 'ai-assistance-4a90a',
    authDomain: 'ai-assistance-4a90a.firebaseapp.com',
    storageBucket: 'ai-assistance-4a90a.appspot.com',
    measurementId: 'G-FZ1F9RNNXM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgEh15-8rGGNfYbmwjNZC1aQuvKGZvGc',
    appId: '1:346213444964:ios:7d14ac42ac373bec079e71',
    messagingSenderId: '346213444964',
    projectId: 'ai-assistance-4a90a',
    storageBucket: 'ai-assistance-4a90a.appspot.com',
    iosBundleId: 'com.ai.ardit.aiAssistant',
  );

}